### ISSUE TITLE
ARM Support?

### ISSUE THREAD

**Issue by daniel-sousa-me** [graysky2/kodi-standalone-service#18]
The readme states

> Users of ARM distros such as Arch ARM, Raspbian, etc. should NOT use these files.

I tried running this in a olinuxino A20 and it seems to work. Why doe you say not to use these files?

**Comment by graysky2** [comment]
I am unfamiliar with that hardware and whatever distro you're running.  The comment is meant to warn users of Arch ARM in particular not to install this since all of the corresponding packages supply their own version of a service.  If you are knowledgeable enough with your distro, feel free to use/modify.

**Comment by nlgranger** [comment]
Could you please just rephrase the readme to reflect what you wrote above?

**Comment by C0rn3j** [comment]
@graysky2 please put this in the PKGBUILD too.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kodi-standalone-service#n7

**Comment by graysky2** [comment]
Why?

**Comment by C0rn3j** [comment]
@graysky2 For the same reason you fixed it in the docs here, I had to go search issues to figure out that a service already ships within the ALARM package.

**Comment by graysky2** [comment]
I still don't understand what you're asking me to do.  The PKGBUILD you linked above is already commented advising not to build for ARM.

**Comment by C0rn3j** [comment]
This issue:

`Users of ARM distros such as Arch ARM, Raspbian, etc. should NOT use these files.`

->

`Users of ARM distros such as Arch ARM, Raspberry Pi OS (formerly Raspbian), etc. should NOT use these files since their official corresponding kodi packages supply their own version of a service. If you are knowledgeable enough with your distro, feel free to use/modify.`

---

PKGBUILD:

`# Do NOT attempt to use this package on Arch ARM! This is only for x86_64.`

->

`???`

I would like if the PKGBUILD similarly also informed that a *service file should already be shipped* in the core ARM distro packages.

**Comment by graysky2** [comment]
Feedback I received from RPiOS users is that they do not have a systemd service, see the readme, so the warning only applies to ArchARM.  I guess I can adjust the commented lines in the x86_64 PKGBUILD to be more clear, but I think that's overkill.

**Comment by C0rn3j** [comment]
I can only vouch for ALARM, but the warning would've saved me a few minutes of time :)
