### ISSUE TITLE
Conflict with ARM packages instead of abusing "arch"?

### ISSUE THREAD

**Issue by M-Reimer** [graysky2/kodi-standalone-service#20]
I'm currently working on merging back some changes I did for "vdr4arch" and one change we had was a different way to prevent conflicts with ARM.

The PKGBUILD should be arch=any as it only contains scripts and nothing else.

To properly prevent installing on ARM, together with the specialized kodi builds there, would be to add something like this to your PKGBUILD:

conflicts=("kodi-c1", "kodi-c2", "kodi-imx", "kodi-odroid", "kodi-rbp", "kodi-rbp-git", "kodi-rbp3", "kodi-rbp4")

**Comment by graysky2** [comment]
I don't want to keep a `conflicts` array updated with all possible Arch ARM packages (and potentially more if it's an Arch ARM clone).  Defining x86_64 in as the valid architecture serves its purpose as users will have to override with a switch or manually edit the PKGBUILD where they would see the [comment](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kodi-standalone-service#n8) warning against as well.  Finally, if they are _really_ intent on installing it on Arch ARM, pacman should error out when installing since they presumabily have an Arch ARM kodi package on their system which also provides `/usr/lib/systemd/system/kodi.service`
