### ISSUE TITLE
Where should I put screen blanking preventing code?

### ISSUE THREAD

**Issue by dbrw** [graysky2/kodi-standalone-service#21]
This is not really an issue, just need some insight to where should I put line like:

```
xset s off -dpms
```

I usually can put this line on my `~/.xinitrc`, can I put this on `/var/lib/kodi/.xinitrc` and make sure it run?

**Comment by graysky2** [comment]
I believe you will need to create `/var/lib/kodi/.xinitrc` containing that line as you suggested.  Try it and let me know.

**Comment by graysky2** [comment]
@dbrw - Still an issue?

**Comment by dbrw** [comment]
I tested it out for a few days to be sure. I think it works. Thank you.

**Comment by dbrw** [comment]
Sorry to comment on this issue because I found something interesting and new issue is not appropriate.

So what I did before actually ran command `xset s off -dpms` manually. Turns out after few reboot, my external display keeps blanking.

I think this is because if you start `/usr/bin/xinit /usr/bin/kodi-standalone -- :0 -nolisten tcp vt1`, xinit do not source file `/var/lib/kodi/.xinitrc` so my screen keep blanking after 5 minutes (default in arch laptop maybe).

After I move the execution of `kodi-standalone` to `/var/lib/kodi/.xinitrc`:
```bash
# on the end of my xinitrc
exec /usr/bin/kodi-standalone
```

and removed it from `/usr/lib/systemd/system/kodi-x11.service`:
```systemd
ExecStart=/usr/bin/xinit -- :0 -nolisten tcp vt1
```

the `.xinitrc` is sourced properly but I wonder if there is any drawback of this approach.

**Comment by graysky2** [comment]
Are using the latest version of this code and did you create the kodi user with the included systemd confs?
The `ExecStart=` you mentioned above is not current.
What is the output of `grep kodi /etc/passwd`

Secondly, since xinit and the subsequent kodi-x11 should both be running as the kodi user, I would think that the $HOMEDIR would be honored.  If you're simply using this code as inspiration for your own setup, that's a different story.

**Comment by dbrw** [comment]
Thank you for your response.

Turned out I was still running the one from kodi-standalone-x11-service. I already update to latest one but still `.xinitrc` is not sourced.

Output of `grep kodi /etc/passwd`:

```
kodi:x:973:973:Kodi User:/var/lib/kodi:/usr/bin/nologin
```

I was also thinking the same, since the service run `/usr/bin/xinit` as kodi user, I thought that it will also sourcing `/var/lib/kodi/.xinitrc` but it didn't.

I found this paragraph on `man xinit`:
```
       If no specific client program is given on the command line, xinit will
       look for a file in the user's home directory called .xinitrc to run as a
       shell script to start  up  client programs.  If no such file exists, xinit
       will use the following as a default:
```

Note that "**If no specific client program is given**" part, I concluded that becasue the service's ExecStart is running `xinit` with `kodi-x11` as its client then `xinit` will not source the `.xinitrc` file. But I can't found verification on this, yet.

I want to use the original service as is because I prefer it to have update if available, so If possible, I don't want to change the service file like what I did.

**Comment by graysky2** [comment]
@dbrw - Stupid question but is `/var/lib/kodi/.xinitrc` 644 for kodi:kodi on your filesystem?
@ghen2 - Any thoughts why xinit isn't sourcing `/var/lib/kodi/.xinitrc`

**Comment by ghen2** [comment]
Because you already specify a program on the xinit command line.  It's either that or parsing .xinitrc, but not both (see `man xinit`).

Regarding DPMS settings, _any_ X client can control that, I believe Kodi takes control of this **if** it's running in full screen mode (as opposed to windowed mode), see https://kodi.wiki/view/Settings/Interface/Screensaver.  At least my screen never goes blank with Kodi's "dim" setting.

Alternatively, you can put screenblanking settings in a server config file under `/etc/X11/xorg.conf.d/`, look for `BlankTime` and friends in `man xorg.conf`.

**Comment by dbrw** [comment]
> @dbrw - Stupid question but is `/var/lib/kodi/.xinitrc` 644 for kodi:kodi on your filesystem?

Here is the file permission:
```
-rw-r--r-- 1 kodi kodi 448 Oct 27 09:01 /var/lib/kodi/.xinitrc
```

Thank you @ghen2 for the explanation, I know where to look for the next step is.

**Comment by sarmong** [comment]
What is the correct way to call startup commands?

What I currently did is modified systemd service to have this:

```
ExecStart=/usr/bin/xinit -- :0 -quiet -nolisten tcp vt1
```
And created `/var/lib/.xinitrc` with this:

```
xsetroot -cursor_name left_ptr
unclutter &
exec /usr/bin/kodi-standalone
```

@graysky2 Is there a better way to achieve what I want? Or maybe it is worth making this change in the repo so that others could take the same approach?
